dist: xenial
language: ruby
rvm:
- 2.5.5
cache:
  bundler: true
addons:
  postgresql: '10'
  apt:
    packages:
    - libarchive-dev
matrix:
  fast_finish: true
env:
  global:
  - REPOS=d-m-u/openshift@updating_faraday
  matrix:
  - TEST_REPO=manageiq-providers-openshift
  - TEST_REPO=manageiq-providers-kubernetes